-- FakeFish 数据库结构定义

CREATE DATABASE IF NOT EXISTS fakefish DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fakefish;

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    gold BIGINT NOT NULL DEFAULT 100,
    best_gold BIGINT NOT NULL DEFAULT 0,
    kills INT NOT NULL DEFAULT 0,
    deaths INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
